[[edge_functions]]
  path = "/*"
  function = "spa-404"
  excludedPath = ["/assets/*", "/api/*", "/.netlify/*", "/robots.txt", "/sitemap.xml", "/sitemap.html", "/favicon*"]

[[redirects]]
  from = "/sitemap.html"
  to = "/sitemap.html"
  status = 200

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
