import { useState, useEffect } from 'react';
import { Home } from './pages/Home';
import { Products } from './pages/Products';
import { Solutions } from './pages/Solutions';
import { ZultysBusinessPhoneSystems } from './pages/ZultysBusinessPhoneSystems';
import { About } from './pages/About';
import { Contact } from './pages/Contact';
import { MXSeries } from './pages/MXSeries';
import { MXSE } from './pages/MXSE';
import { ZIP49G } from './pages/ZIP49G';
import { ZIP47G } from './pages/ZIP47G';
import { ZIP45G } from './pages/ZIP45G';
import { ZIP43G } from './pages/ZIP43G';
import { ZAC } from './pages/ZAC';
import { MXmobile } from './pages/MXmobile';
import { MXconference } from './pages/MXconference';
import { Healthcare } from './pages/Healthcare';
import { ProfessionalServices } from './pages/ProfessionalServices';
import { RealEstate } from './pages/RealEstate';
import { Education } from './pages/Education';
import { RetailAutomotive } from './pages/RetailAutomotive';
import { Enterprise } from './pages/Enterprise';
import { MultiLocation } from './pages/MultiLocation';
import { CloudServices } from './pages/CloudServices';
import { OnPremise } from './pages/OnPremise';
import { Hybrid } from './pages/Hybrid';
import { ContactCenter } from './pages/ContactCenter';
import { Support } from './pages/Support';
import { Installation } from './pages/Installation';
import { Training } from './pages/Training';
import { Addison } from './pages/Addison';
import { Aledo } from './pages/Aledo';
import { Springtown } from './pages/Springtown';
import { Granbury } from './pages/Granbury';
import { GlenRose } from './pages/GlenRose';
import { Godley } from './pages/Godley';
import { Grandview } from './pages/Grandview';
import { Venus } from './pages/Venus';
import { Maypearl } from './pages/Maypearl';
import { Italy } from './pages/Italy';
import { Milford } from './pages/Milford';
import { Palmer } from './pages/Palmer';
import { Sitemap } from './pages/Sitemap';
import { SmallBusiness } from './pages/SmallBusiness';
import { Blog } from './pages/Blog';
import { BlogBestChoice } from './pages/BlogBestChoice';
import { BlogCloudVsOnPremise } from './pages/BlogCloudVsOnPremise';
import { BlogNetworkOptimization } from './pages/BlogNetworkOptimization';
import { ZultysVsCompetitors } from './pages/ZultysVsCompetitors';
import { ZultysVsRingCentral } from './pages/ZultysVsRingCentral';
import { ZultysVs8x8 } from './pages/ZultysVs8x8';
import { ZultysVsTeams } from './pages/ZultysVsTeams';
import { ZultysVsVonage } from './pages/ZultysVsVonage';
import { FAQPage } from './pages/FAQPage';
import { HIPAACompliance } from './pages/HIPAACompliance';
import { Pricing } from './pages/Pricing';
import { FreeAudit } from './pages/FreeAudit';
import { CaseStudies } from './pages/CaseStudies';
import { VoIPGlossary } from './pages/VoIPGlossary';
import { OurTeam } from './pages/OurTeam';
import { CertificationsAwards } from './pages/CertificationsAwards';
import { UserGuides } from './pages/UserGuides';
import { PrivacyPolicy } from './pages/PrivacyPolicy';
import { TermsOfService } from './pages/TermsOfService';
import { ZultysVsAvaya } from './pages/ZultysVsAvaya';
import { ZultysVsCisco } from './pages/ZultysVsCisco';
import { ZultysVsMitel } from './pages/ZultysVsMitel';
import { ZultysMigrationGuide } from './pages/ZultysMigrationGuide';
import { ZultysCRMIntegration } from './pages/ZultysCRMIntegration';
import { ZultysVsZoom } from './pages/ZultysVsZoom';
import { ZultysVsGoTo } from './pages/ZultysVsGoTo';
import { ZultysVsNextiva } from './pages/ZultysVsNextiva';
import { RemoteWorkSolutions } from './pages/RemoteWorkSolutions';
import { VoIPSecurity } from './pages/VoIPSecurity';
import { ZultysVsDialpad } from './pages/ZultysVsDialpad';
import { ZultysVsIntermedia } from './pages/ZultysVsIntermedia';
import { LegalFirms } from './pages/LegalFirms';
import { FinancialServices } from './pages/FinancialServices';
import { ManufacturingLogistics } from './pages/ManufacturingLogistics';
import { ZultysVsComcast } from './pages/ZultysVsComcast';
import { ZultysVsSpectrum } from './pages/ZultysVsSpectrum';
import { ZultysVsATT } from './pages/ZultysVsATT';
import { HospitalitySolutions } from './pages/HospitalitySolutions';
import { NonProfitSolutions } from './pages/NonProfitSolutions';
import { ZultysVsOoma } from './pages/ZultysVsOoma';
import { EducationSolutions } from './pages/EducationSolutions';
import { RealEstateSolutions } from './pages/RealEstateSolutions';
import { RetailSolutions } from './pages/RetailSolutions';
import { Mesquite } from './pages/Mesquite';
import { Garland } from './pages/Garland';
import { McKinney } from './pages/McKinney';
import { Denton } from './pages/Denton';
import { Lewisville } from './pages/Lewisville';
import { Allen } from './pages/Allen';
import { Mansfield } from './pages/Mansfield';
import { Rowlett } from './pages/Rowlett';
import { CedarHill } from './pages/CedarHill';
import { DeSoto } from './pages/DeSoto';
import { Coppell } from './pages/Coppell';
import { Duncanville } from './pages/Duncanville';
import { Lancaster } from './pages/Lancaster';
import { TheColony } from './pages/TheColony';
import { LittleElm } from './pages/LittleElm';
import { Wylie } from './pages/Wylie';
import { Rockwall } from './pages/Rockwall';
import { Forney } from './pages/Forney';
import { Midlothian } from './pages/Midlothian';
import { Waxahachie } from './pages/Waxahachie';
import { Ennis } from './pages/Ennis';
import { Cleburne } from './pages/Cleburne';
import { Weatherford } from './pages/Weatherford';
import { Burleson } from './pages/Burleson';
import { Terrell } from './pages/Terrell';
import { Prosper } from './pages/Prosper';
import { Murphy } from './pages/Murphy';
import { Sachse } from './pages/Sachse';
import { Seagoville } from './pages/Seagoville';
import { BalchSprings } from './pages/BalchSprings';
import { Celina } from './pages/Celina';
import { Princeton } from './pages/Princeton';
import { Anna } from './pages/Anna';
import { Melissa } from './pages/Melissa';
import { RoyseCity } from './pages/RoyseCity';
import { Fate } from './pages/Fate';
import { Heath } from './pages/Heath';
import { Sunnyvale } from './pages/Sunnyvale';
import { Crandall } from './pages/Crandall';
import { Lavon } from './pages/Lavon';
import { RedOak } from './pages/RedOak';
import { Ovilla } from './pages/Ovilla';
import { GlennHeights } from './pages/GlennHeights';
import { Hutchins } from './pages/Hutchins';
import { Wilmer } from './pages/Wilmer';
import { Kaufman } from './pages/Kaufman';
import { PilotPoint } from './pages/PilotPoint';
import { Sanger } from './pages/Sanger';
import { Aubrey } from './pages/Aubrey';
import { Alvarado } from './pages/Alvarado';
import { Decatur } from './pages/Decatur';
import { Bridgeport } from './pages/Bridgeport';
import { Justin } from './pages/Justin';
import { Krum } from './pages/Krum';
import { Ponder } from './pages/Ponder';
import { TrophyClub } from './pages/TrophyClub';
import { Roanoke } from './pages/Roanoke';
import { Argyle } from './pages/Argyle';
import { Kennedale } from './pages/Kennedale';
import { ForestHill } from './pages/ForestHill';
import { BlueMound } from './pages/BlueMound';
import { Azle } from './pages/Azle';
import { Bartonville } from './pages/Bartonville';
import { Bowie } from './pages/Bowie';
import { Boyd } from './pages/Boyd';
import { Brock } from './pages/Brock';
import { Crowley } from './pages/Crowley';
import { Haslet } from './pages/Haslet';
import { Joshua } from './pages/Joshua';
import { LakeWorth } from './pages/LakeWorth';
import { Lakeside } from './pages/Lakeside';
import { NotFound } from './pages/NotFound';
import { Z23GE } from './pages/Z23GE';
import { Z22G } from './pages/Z22G';
import { Z21i } from './pages/Z21i';
import { Gateways } from './pages/Gateways';
import { DallasZultysPhones } from './pages/DallasZultysPhones';
import { Arlington } from './pages/Arlington';
import { Plano } from './pages/Plano';
import { Irving } from './pages/Irving';
import { Frisco } from './pages/Frisco';
import { GrandPrairie } from './pages/GrandPrairie';
import { Southlake } from './pages/Southlake';
import { Grapevine } from './pages/Grapevine';
import { Carrollton } from './pages/Carrollton';
import { Richardson } from './pages/Richardson';
import { Hurst } from './pages/Hurst';
import { Bedford } from './pages/Bedford';
import { Euless } from './pages/Euless';
import { NorthRichlandHills } from './pages/NorthRichlandHills';
import { FlowerMound } from './pages/FlowerMound';
import { Colleyville } from './pages/Colleyville';
import { Keller } from './pages/Keller';
import { Saginaw } from './pages/Saginaw';
import { HaltomCity } from './pages/HaltomCity';
import { Watauga } from './pages/Watauga';
import { Benbrook } from './pages/Benbrook';
import { WestworthVillage } from './pages/WestworthVillage';
import { WhiteSettlement } from './pages/WhiteSettlement';
import { RiverOaks } from './pages/RiverOaks';
import { HudsonOaks } from './pages/HudsonOaks';
import { WillowPark } from './pages/WillowPark';
import { Everman } from './pages/Everman';
import { Pantego } from './pages/Pantego';
import { DalworthingtonGardens } from './pages/DalworthingtonGardens';
import { WestoverHills } from './pages/WestoverHills';
import { EdgecliffVillage } from './pages/EdgecliffVillage';
import { RichlandHills } from './pages/RichlandHills';
import { SansomPark } from './pages/SansomPark';
import { Reno } from './pages/Reno';
import { VanAlstyne } from './pages/VanAlstyne';
import { Leonard } from './pages/Leonard';
import { Farmersville } from './pages/Farmersville';
import { Howe } from './pages/Howe';
import { Whitewright } from './pages/Whitewright';
import { Gunter } from './pages/Gunter';
import { Collinsville } from './pages/Collinsville';
import { Tioga } from './pages/Tioga';
import { TomBean } from './pages/TomBean';
import { Trenton } from './pages/Trenton';
import { Savoy } from './pages/Savoy';
import { Bells } from './pages/Bells';
import { BlueRidge } from './pages/BlueRidge';
import { Ector } from './pages/Ector';
import { Ravenna } from './pages/Ravenna';
import { Bonham } from './pages/Bonham';
import { HoneyGrove } from './pages/HoneyGrove';
import { Ladonia } from './pages/Ladonia';
import { Windom } from './pages/Windom';
import { DoddCity } from './pages/DoddCity';
import { Merit } from './pages/Merit';
import { Celeste } from './pages/Celeste';
import { WolfeCity } from './pages/WolfeCity';
import { CaddoMills } from './pages/CaddoMills';
import { Nevada } from './pages/Nevada';
import { Josephine } from './pages/Josephine';
import { Bailey } from './pages/Bailey';
import { Randolph } from './pages/Randolph';
import { Telephone } from './pages/Telephone';
import { Ivanhoe } from './pages/Ivanhoe';
import { Gober } from './pages/Gober';
import { Toaster } from 'sonner';
import { QuoteProvider } from './context/QuoteContext';
import { QuotePopupWrapper } from './components/QuotePopupWrapper';

export default function App() {
  const [currentPath, setCurrentPath] = useState(window.location.pathname);

  useEffect(() => {
    const handlePopState = () => {
      setCurrentPath(window.location.pathname);
    };

    window.addEventListener('popstate', handlePopState);
    return () => window.removeEventListener('popstate', handlePopState);
  }, []);

  // Simple routing logic
  const renderPage = () => {
    // Normalize path: remove trailing slash and convert to lowercase for robustness
    const normalizedPath = currentPath.toLowerCase().endsWith('/') && currentPath.length > 1 
      ? currentPath.toLowerCase().slice(0, -1) 
      : currentPath.toLowerCase();

    // Exact matches
    if (normalizedPath === '/' || normalizedPath === '/index.html') return <Home />;
    if (normalizedPath === '/products') return <Products />;
    if (normalizedPath === '/solutions') return <Solutions />;
    if (normalizedPath === '/about') return <About />;
    if (normalizedPath === '/contact') return <Contact />;
    if (normalizedPath === '/blog') return <Blog />;
    if (normalizedPath === '/blog/why-zultys-is-the-best-choice-for-dfw-small-businesses') return <BlogBestChoice />;
    if (normalizedPath === '/blog/on-premise-vs-cloud-which-zultys-deployment-is-right-for-you') return <BlogCloudVsOnPremise />;
    if (normalizedPath === '/blog/how-to-optimize-your-office-network-for-voip-performance') return <BlogNetworkOptimization />;
    
    if (normalizedPath === '/zultys-vs-competitors' || normalizedPath === '/zultys-vs-competition') return <ZultysVsCompetitors />;
    if (normalizedPath === '/zultys-vs-ringcentral') return <ZultysVsRingCentral />;
    if (normalizedPath === '/zultys-vs-8x8') return <ZultysVs8x8 />;
    if (normalizedPath === '/zultys-vs-microsoft-teams') return <ZultysVsTeams />;
    if (normalizedPath === '/zultys-vs-vonage') return <ZultysVsVonage />;
    if (normalizedPath === '/zultys-faq') return <FAQPage />;
    if (normalizedPath === '/hipaa-compliant-voip') return <HIPAACompliance />;
    if (normalizedPath === '/zultys-pricing') return <Pricing />;
    if (normalizedPath === '/free-voip-site-audit') return <FreeAudit />;
    if (normalizedPath === '/case-studies') return <CaseStudies />;
    if (normalizedPath === '/voip-glossary') return <VoIPGlossary />;
    if (normalizedPath === '/our-team') return <OurTeam />;
    if (normalizedPath === '/certifications-awards') return <CertificationsAwards />;
    if (normalizedPath === '/zultys-user-guides') return <UserGuides />;
    if (normalizedPath === '/privacy') return <PrivacyPolicy />;
    if (normalizedPath === '/terms') return <TermsOfService />;
    if (normalizedPath === '/zultys-vs-avaya') return <ZultysVsAvaya />;
    if (normalizedPath === '/zultys-vs-cisco-webex') return <ZultysVsCisco />;
    if (normalizedPath === '/zultys-vs-mitel') return <ZultysVsMitel />;
    if (normalizedPath === '/zultys-migration-guide-dfw') return <ZultysMigrationGuide />;
    if (normalizedPath === '/zultys-crm-integration-guide') return <ZultysCRMIntegration />;
    if (normalizedPath === '/zultys-vs-zoom-phone') return <ZultysVsZoom />;
    if (normalizedPath === '/zultys-vs-gotoconnect') return <ZultysVsGoTo />;
    if (normalizedPath === '/zultys-vs-nextiva') return <ZultysVsNextiva />;
    if (normalizedPath === '/remote-work-solutions') return <RemoteWorkSolutions />;
    if (normalizedPath === '/voip-security-encryption') return <VoIPSecurity />;
    if (normalizedPath === '/zultys-vs-dialpad') return <ZultysVsDialpad />;
    if (normalizedPath === '/zultys-vs-intermedia') return <ZultysVsIntermedia />;
    if (normalizedPath === '/zultys-for-legal-firms') return <LegalFirms />;
    if (normalizedPath === '/zultys-for-financial-services') return <FinancialServices />;
    if (normalizedPath === '/zultys-for-manufacturing-logistics') return <ManufacturingLogistics />;
    if (normalizedPath === '/zultys-vs-comcast-business') return <ZultysVsComcast />;
    if (normalizedPath === '/zultys-vs-spectrum-business') return <ZultysVsSpectrum />;
    if (normalizedPath === '/zultys-vs-att-business') return <ZultysVsATT />;
    if (normalizedPath === '/zultys-for-hospitality') return <HospitalitySolutions />;
    if (normalizedPath === '/zultys-for-non-profits') return <NonProfitSolutions />;
    if (normalizedPath === '/zultys-vs-ooma-office') return <ZultysVsOoma />;
    if (normalizedPath === '/zultys-for-education') return <EducationSolutions />;
    if (normalizedPath === '/zultys-for-real-estate') return <RealEstateSolutions />;
    if (normalizedPath === '/zultys-for-retail') return <RetailSolutions />;
    // City Pages with Aliases
    if (normalizedPath === '/mesquite-zultys-phone-systems' || normalizedPath === '/mesquite') return <Mesquite />;
    if (normalizedPath === '/garland-business-voip' || normalizedPath === '/garland') return <Garland />;
    if (normalizedPath === '/mckinney-zultys-dealer' || normalizedPath === '/mckinney') return <McKinney />;
    if (normalizedPath === '/denton-business-phone-systems' || normalizedPath === '/denton') return <Denton />;
    if (normalizedPath === '/lewisville-voip-solutions' || normalizedPath === '/lewisville') return <Lewisville />;
    if (normalizedPath === '/allen-tx-zultys-voip' || normalizedPath === '/allen') return <Allen />;
    if (normalizedPath === '/mansfield-tx-zultys-phone-systems' || normalizedPath === '/mansfield') return <Mansfield />;
    if (normalizedPath === '/rowlett-tx-zultys-dealer' || normalizedPath === '/rowlett') return <Rowlett />;
    if (normalizedPath === '/cedar-hill-tx-zultys-voip' || normalizedPath === '/cedar-hill') return <CedarHill />;
    if (normalizedPath === '/desoto-tx-zultys-phone-systems' || normalizedPath === '/desoto') return <DeSoto />;
    if (normalizedPath === '/coppell-tx-zultys-phone-systems' || normalizedPath === '/coppell') return <Coppell />;
    if (normalizedPath === '/duncanville-tx-zultys-voip' || normalizedPath === '/duncanville') return <Duncanville />;
    if (normalizedPath === '/lancaster-tx-zultys-dealer' || normalizedPath === '/lancaster') return <Lancaster />;
    if (normalizedPath === '/the-colony-tx-zultys-voip' || normalizedPath === '/the-colony') return <TheColony />;
    if (normalizedPath === '/little-elm-tx-zultys-phone-systems' || normalizedPath === '/little-elm') return <LittleElm />;
    if (normalizedPath === '/wylie-tx-zultys-phone-systems' || normalizedPath === '/wylie') return <Wylie />;
    if (normalizedPath === '/rockwall-tx-zultys-phone-systems' || normalizedPath === '/rockwall') return <Rockwall />;
    if (normalizedPath === '/forney-tx-zultys-phone-systems' || normalizedPath === '/forney') return <Forney />;
    if (normalizedPath === '/midlothian-tx-zultys-phone-systems' || normalizedPath === '/midlothian') return <Midlothian />;
    if (normalizedPath === '/waxahachie-tx-zultys-phone-systems' || normalizedPath === '/waxahachie') return <Waxahachie />;
    if (normalizedPath === '/ennis-tx-zultys-phone-systems' || normalizedPath === '/ennis') return <Ennis />;
    if (normalizedPath === '/cleburne-tx-zultys-phone-systems' || normalizedPath === '/cleburne') return <Cleburne />;
    if (normalizedPath === '/weatherford-tx-zultys-phone-systems' || normalizedPath === '/weatherford') return <Weatherford />;
    if (normalizedPath === '/burleson-tx-zultys-phone-systems' || normalizedPath === '/burleson') return <Burleson />;
    if (normalizedPath === '/terrell-tx-zultys-phone-systems' || normalizedPath === '/terrell') return <Terrell />;
    if (normalizedPath === '/prosper-tx-zultys-phone-systems' || normalizedPath === '/prosper') return <Prosper />;
    if (normalizedPath === '/murphy-tx-zultys-voip' || normalizedPath === '/murphy') return <Murphy />;
    if (normalizedPath === '/sachse-tx-zultys-dealer' || normalizedPath === '/sachse') return <Sachse />;
    if (normalizedPath === '/seagoville-tx-zultys-phone-systems' || normalizedPath === '/seagoville') return <Seagoville />;
    if (normalizedPath === '/balch-springs-tx-zultys-voip' || normalizedPath === '/balch-springs') return <BalchSprings />;
    if (normalizedPath === '/celina-tx-zultys-phone-systems' || normalizedPath === '/celina') return <Celina />;
    if (normalizedPath === '/princeton-tx-zultys-phone-systems' || normalizedPath === '/princeton') return <Princeton />;
    if (normalizedPath === '/anna-tx-zultys-phone-systems' || normalizedPath === '/anna') return <Anna />;
    if (normalizedPath === '/melissa-tx-zultys-phone-systems' || normalizedPath === '/melissa') return <Melissa />;
    if (normalizedPath === '/royse-city-tx-zultys-phone-systems' || normalizedPath === '/royse-city') return <RoyseCity />;
    if (normalizedPath === '/fate-tx-zultys-phone-systems' || normalizedPath === '/fate') return <Fate />;
    if (normalizedPath === '/heath-tx-zultys-phone-systems' || normalizedPath === '/heath') return <Heath />;
    if (normalizedPath === '/sunnyvale-tx-zultys-phone-systems' || normalizedPath === '/sunnyvale') return <Sunnyvale />;
    if (normalizedPath === '/crandall-tx-zultys-phone-systems' || normalizedPath === '/crandall') return <Crandall />;
    if (normalizedPath === '/lavon-tx-zultys-phone-systems' || normalizedPath === '/lavon') return <Lavon />;
    if (normalizedPath === '/red-oak-tx-zultys-phone-systems' || normalizedPath === '/red-oak') return <RedOak />;
    if (normalizedPath === '/ovilla-tx-zultys-phone-systems' || normalizedPath === '/ovilla') return <Ovilla />;
    if (normalizedPath === '/glenn-heights-tx-zultys-phone-systems' || normalizedPath === '/glenn-heights') return <GlennHeights />;
    if (normalizedPath === '/hutchins-tx-zultys-phone-systems' || normalizedPath === '/hutchins') return <Hutchins />;
    if (normalizedPath === '/wilmer-tx-zultys-phone-systems' || normalizedPath === '/wilmer') return <Wilmer />;
    if (normalizedPath === '/kaufman-tx-zultys-phone-systems' || normalizedPath === '/kaufman') return <Kaufman />;
    if (normalizedPath === '/pilot-point-tx-zultys-phone-systems' || normalizedPath === '/pilot-point') return <PilotPoint />;
    if (normalizedPath === '/sanger-tx-zultys-phone-systems' || normalizedPath === '/sanger') return <Sanger />;
    if (normalizedPath === '/aubrey-tx-zultys-phone-systems' || normalizedPath === '/aubrey') return <Aubrey />;
    if (normalizedPath === '/alvarado-tx-zultys-phone-systems' || normalizedPath === '/alvarado') return <Alvarado />;
    if (normalizedPath === '/decatur-tx-zultys-phone-systems' || normalizedPath === '/decatur') return <Decatur />;
    if (normalizedPath === '/bridgeport-tx-zultys-phone-systems' || normalizedPath === '/bridgeport') return <Bridgeport />;
    if (normalizedPath === '/justin-tx-zultys-phone-systems' || normalizedPath === '/justin') return <Justin />;
    if (normalizedPath === '/krum-tx-zultys-phone-systems' || normalizedPath === '/krum') return <Krum />;
    if (normalizedPath === '/ponder-tx-zultys-phone-systems' || normalizedPath === '/ponder') return <Ponder />;
    if (normalizedPath === '/trophy-club-tx-zultys-phone-systems' || normalizedPath === '/trophy-club') return <TrophyClub />;
    if (normalizedPath === '/roanoke-tx-zultys-phone-systems' || normalizedPath === '/roanoke') return <Roanoke />;
    if (normalizedPath === '/argyle-tx-zultys-phone-systems' || normalizedPath === '/argyle') return <Argyle />;
    if (normalizedPath === '/kennedale-tx-zultys-phone-systems' || normalizedPath === '/kennedale') return <Kennedale />;
    if (normalizedPath === '/forest-hill-tx-zultys-phone-systems' || normalizedPath === '/forest-hill') return <ForestHill />;
    if (normalizedPath === '/azle-tx-zultys-phone-systems' || normalizedPath === '/azle') return <Azle />;
    if (normalizedPath === '/bartonville-tx-zultys-phone-systems' || normalizedPath === '/bartonville') return <Bartonville />;
    if (normalizedPath === '/bowie-tx-zultys-phone-systems' || normalizedPath === '/bowie') return <Bowie />;
    if (normalizedPath === '/boyd-tx-zultys-phone-systems' || normalizedPath === '/boyd') return <Boyd />;
    if (normalizedPath === '/brock-tx-zultys-phone-systems' || normalizedPath === '/brock') return <Brock />;
    if (normalizedPath === '/crowley-tx-zultys-phone-systems' || normalizedPath === '/crowley') return <Crowley />;
    if (normalizedPath === '/haslet-tx-zultys-phone-systems' || normalizedPath === '/haslet') return <Haslet />;
    if (normalizedPath === '/joshua-tx-zultys-phone-systems' || normalizedPath === '/joshua') return <Joshua />;
    if (normalizedPath === '/lake-worth-tx-zultys-phone-systems' || normalizedPath === '/lake-worth') return <LakeWorth />;
    if (normalizedPath === '/lakeside-tx-zultys-phone-systems' || normalizedPath === '/lakeside') return <Lakeside />;
    
    if (normalizedPath === '/arlington-ip-pbx' || normalizedPath === '/arlington') return <Arlington />;
    if (normalizedPath === '/plano-zultys-dealer' || normalizedPath === '/plano') return <Plano />;
    if (normalizedPath === '/irving-business-phone-systems' || normalizedPath === '/irving') return <Irving />;
    if (normalizedPath === '/frisco-voip-solutions' || normalizedPath === '/frisco') return <Frisco />;
    if (normalizedPath === '/grand-prairie-zultys' || normalizedPath === '/grand-prairie') return <GrandPrairie />;
    if (normalizedPath === '/southlake-ip-phones' || normalizedPath === '/southlake') return <Southlake />;
    if (normalizedPath === '/grapevine-business-voip' || normalizedPath === '/grapevine') return <Grapevine />;
    if (normalizedPath === '/carrollton-zultys' || normalizedPath === '/carrollton') return <Carrollton />;
    if (normalizedPath === '/richardson-phone-systems' || normalizedPath === '/richardson') return <Richardson />;
    if (normalizedPath === '/hurst-ip-pbx' || normalizedPath === '/hurst') return <Hurst />;
    if (normalizedPath === '/bedford-zultys-solutions' || normalizedPath === '/bedford') return <Bedford />;
    if (normalizedPath === '/euless-business-phones' || normalizedPath === '/euless') return <Euless />;
    
    if (normalizedPath === '/north-richland-hills-zultys' || normalizedPath === '/north-richland-hills' || normalizedPath === '/north-richland-hills-voip') return <NorthRichlandHills />;
    if (normalizedPath === '/flower-mound-business-phones' || normalizedPath === '/flower-mound') return <FlowerMound />;
    if (normalizedPath === '/colleyville-voip' || normalizedPath === '/colleyville' || normalizedPath === '/colleyville-ip-phones') return <Colleyville />;
    if (normalizedPath === '/keller-zultys-dealer' || normalizedPath === '/keller') return <Keller />;
    if (normalizedPath === '/saginaw-business-communications' || normalizedPath === '/saginaw') return <Saginaw />;
    if (normalizedPath === '/haltom-city-zultys' || normalizedPath === '/haltom-city') return <HaltomCity />;
    if (normalizedPath === '/springtown-tx-zultys-phone-systems' || normalizedPath === '/springtown') return <Springtown />;
    if (normalizedPath === '/granbury-tx-zultys-phone-systems' || normalizedPath === '/granbury') return <Granbury />;
    if (normalizedPath === '/glen-rose-tx-zultys-phone-systems' || normalizedPath === '/glen-rose') return <GlenRose />;
    if (normalizedPath === '/godley-tx-zultys-phone-systems' || normalizedPath === '/godley') return <Godley />;
    if (normalizedPath === '/grandview-tx-zultys-phone-systems' || normalizedPath === '/grandview') return <Grandview />;
    if (normalizedPath === '/venus-tx-zultys-phone-systems' || normalizedPath === '/venus') return <Venus />;
    if (normalizedPath === '/maypearl-tx-zultys-phone-systems' || normalizedPath === '/maypearl') return <Maypearl />;
    if (normalizedPath === '/italy-tx-zultys-phone-systems' || normalizedPath === '/italy') return <Italy />;
    if (normalizedPath === '/milford-tx-zultys-phone-systems' || normalizedPath === '/milford') return <Milford />;
    if (normalizedPath === '/palmer-tx-zultys-phone-systems' || normalizedPath === '/palmer') return <Palmer />;
    if (normalizedPath === '/watauga-voip-solutions' || normalizedPath === '/watauga') return <Watauga />;
    if (normalizedPath === '/benbrook-phone-systems' || normalizedPath === '/benbrook') return <Benbrook />;
    if (normalizedPath === '/westworth-village-zultys' || normalizedPath === '/westworth-village') return <WestworthVillage />;
    if (normalizedPath === '/white-settlement-business-phones' || normalizedPath === '/white-settlement') return <WhiteSettlement />;
    if (normalizedPath === '/river-oaks-zultys' || normalizedPath === '/river-oaks') return <RiverOaks />;
    if (normalizedPath === '/hudson-oaks-tx-zultys-phone-systems' || normalizedPath === '/hudson-oaks') return <HudsonOaks />;
    if (normalizedPath === '/willow-park-tx-zultys-phone-systems' || normalizedPath === '/willow-park') return <WillowPark />;
    if (normalizedPath === '/everman-tx-zultys-phone-systems' || normalizedPath === '/everman') return <Everman />;
    if (normalizedPath === '/pantego-tx-zultys-phone-systems' || normalizedPath === '/pantego') return <Pantego />;
    if (normalizedPath === '/dalworthington-gardens-tx-zultys-phone-systems' || normalizedPath === '/dalworthington-gardens') return <DalworthingtonGardens />;
    if (normalizedPath === '/westover-hills-tx-zultys-phone-systems' || normalizedPath === '/westover-hills') return <WestoverHills />;
    if (normalizedPath === '/edgecliff-village-tx-zultys-phone-systems' || normalizedPath === '/edgecliff-village') return <EdgecliffVillage />;
    if (normalizedPath === '/richland-hills-tx-zultys-phone-systems' || normalizedPath === '/richland-hills') return <RichlandHills />;
    if (normalizedPath === '/sansom-park-tx-zultys-phone-systems' || normalizedPath === '/sansom-park') return <SansomPark />;
    if (normalizedPath === '/reno-tx-zultys-phone-systems' || normalizedPath === '/reno') return <Reno />;
    if (normalizedPath === '/van-alstyne-tx-zultys-phone-systems' || normalizedPath === '/van-alstyne') return <VanAlstyne />;
    if (normalizedPath === '/leonard-tx-zultys-phone-systems' || normalizedPath === '/leonard') return <Leonard />;
    if (normalizedPath === '/farmersville-tx-zultys-phone-systems' || normalizedPath === '/farmersville') return <Farmersville />;
    if (normalizedPath === '/howe-tx-zultys-phone-systems' || normalizedPath === '/howe') return <Howe />;
    if (normalizedPath === '/whitewright-tx-zultys-phone-systems' || normalizedPath === '/whitewright') return <Whitewright />;
    if (normalizedPath === '/gunter-tx-zultys-phone-systems' || normalizedPath === '/gunter') return <Gunter />;
    if (normalizedPath === '/collinsville-tx-zultys-phone-systems' || normalizedPath === '/collinsville') return <Collinsville />;
    if (normalizedPath === '/tioga-tx-zultys-phone-systems' || normalizedPath === '/tioga') return <Tioga />;
    if (normalizedPath === '/tom-bean-tx-zultys-phone-systems' || normalizedPath === '/tom-bean') return <TomBean />;
    if (normalizedPath === '/trenton-tx-zultys-phone-systems' || normalizedPath === '/trenton') return <Trenton />;
    if (normalizedPath === '/savoy-tx-zultys-phone-systems' || normalizedPath === '/savoy') return <Savoy />;
    if (normalizedPath === '/bells-tx-zultys-phone-systems' || normalizedPath === '/bells') return <Bells />;
    if (normalizedPath === '/blue-ridge-tx-zultys-phone-systems' || normalizedPath === '/blue-ridge') return <BlueRidge />;
    if (normalizedPath === '/ector-tx-zultys-phone-systems' || normalizedPath === '/ector') return <Ector />;
    if (normalizedPath === '/ravenna-tx-zultys-phone-systems' || normalizedPath === '/ravenna') return <Ravenna />;
    if (normalizedPath === '/bonham-tx-zultys-phone-systems' || normalizedPath === '/bonham') return <Bonham />;
    if (normalizedPath === '/honey-grove-tx-zultys-phone-systems' || normalizedPath === '/honey-grove') return <HoneyGrove />;
    if (normalizedPath === '/ladonia-tx-zultys-phone-systems' || normalizedPath === '/ladonia') return <Ladonia />;
    if (normalizedPath === '/windom-tx-zultys-phone-systems' || normalizedPath === '/windom') return <Windom />;
    if (normalizedPath === '/dodd-city-tx-zultys-phone-systems' || normalizedPath === '/dodd-city') return <DoddCity />;
    if (normalizedPath === '/merit-tx-zultys-phone-systems' || normalizedPath === '/merit') return <Merit />;
    if (normalizedPath === '/celeste-tx-zultys-phone-systems' || normalizedPath === '/celeste') return <Celeste />;
    if (normalizedPath === '/wolfe-city-tx-zultys-phone-systems' || normalizedPath === '/wolfe-city') return <WolfeCity />;
    if (normalizedPath === '/caddo-mills-tx-zultys-phone-systems' || normalizedPath === '/caddo-mills') return <CaddoMills />;
    if (normalizedPath === '/nevada-tx-zultys-phone-systems' || normalizedPath === '/nevada') return <Nevada />;
    if (normalizedPath === '/josephine-tx-zultys-phone-systems' || normalizedPath === '/josephine') return <Josephine />;
    if (normalizedPath === '/bailey-tx-zultys-phone-systems' || normalizedPath === '/bailey') return <Bailey />;
    if (normalizedPath === '/randolph-tx-zultys-phone-systems' || normalizedPath === '/randolph') return <Randolph />;
    if (normalizedPath === '/telephone-tx-zultys-phone-systems' || normalizedPath === '/telephone') return <Telephone />;
    if (normalizedPath === '/ivanhoe-tx-zultys-phone-systems' || normalizedPath === '/ivanhoe') return <Ivanhoe />;
    if (normalizedPath === '/gober-tx-zultys-phone-systems' || normalizedPath === '/gober') return <Gober />;
    
    // SEO URLs from user list
    if (normalizedPath === '/dallas-zultys-phones' || normalizedPath === '/dallas') return <DallasZultysPhones />;
    if (normalizedPath === '/fort-worth-zultys-systems' || normalizedPath === '/fort-worth') return <ZultysBusinessPhoneSystems />;
    if (normalizedPath === '/fort-worth-zultys-business-phone-systems') return <ZultysBusinessPhoneSystems />;
    if (normalizedPath === '/fort-worth-zultys-voip-phone-system') return <ZultysBusinessPhoneSystems />;
    if (normalizedPath === '/dallas-zultys-cloud-phones') return <CloudServices />;
    if (normalizedPath === '/fort-worth-zultys-cloud-phone-system') return <CloudServices />;
    if (normalizedPath === '/fort-worth-zultys-video-conferencing-system') return <MXconference />;
    if (normalizedPath === '/fort-worth-zultys-mx-series') return <MXSeries />;
    if (normalizedPath === '/fort-worth-zultys-mx-se') return <MXSE />;
    if (normalizedPath === '/fort-worth-zultys-mxmobile' || normalizedPath === '/fort-worth-zultys-mobile-zac') return <MXmobile />;
    if (normalizedPath === '/fort-worth-zultys-mxconference') return <MXconference />;
    if (normalizedPath === '/fort-worth-zultys-zac') return <ZAC />;
    if (normalizedPath === '/zultys-cloud-services') return <CloudServices />;
    if (normalizedPath === '/fort-worth-zultys-cloud-services') return <CloudServices />;
    if (normalizedPath === '/zultys-ip-phones') return <Products />;
    if (normalizedPath === '/fort-worth-zultys-zip-49g-phone') return <ZIP49G />;
    if (normalizedPath === '/fort-worth-zultys-zip-47g-phone') return <ZIP47G />;
    if (normalizedPath === '/fort-worth-zultys-zip-45g-phone') return <ZIP45G />;
    if (normalizedPath === '/fort-worth-zultys-zip-43g-phone') return <ZIP43G />;
    if (normalizedPath === '/fort-worth-zultys-z-23ge-phone' || normalizedPath === '/fort-worth-zultys-z23g-phone') return <Z23GE />;
    if (normalizedPath === '/fort-worth-zultys-z-22g-phone') return <Z22G />;
    if (normalizedPath === '/fort-worth-zultys-z-21i-phone') return <Z21i />;
    if (normalizedPath === '/fort-worth-zultys-gateways') return <Gateways />;
    if (normalizedPath === '/fort-worth-zultys-phone-system-small-business' || normalizedPath === '/fort-worth-zultys-small-business') return <SmallBusiness />;
    if (normalizedPath === '/fort-worth-zultys-healthcare') return <Healthcare />;
    if (normalizedPath === '/fort-worth-zultys-education') return <Education />;
    if (normalizedPath === '/fort-worth-zultys-professional-services') return <ProfessionalServices />;
    if (normalizedPath === '/fort-worth-zultys-real-estate') return <RealEstate />;
    if (normalizedPath === '/fort-worth-zultys-retail-automotive') return <RetailAutomotive />;
    if (normalizedPath === '/fort-worth-zultys-multi-location') return <MultiLocation />;
    if (normalizedPath === '/fort-worth-zultys-enterprise') return <Enterprise />;
    if (normalizedPath === '/sitemap.html' || normalizedPath === '/sitemap') return <Sitemap />;
    
    // Legacy/Other paths
    if (normalizedPath === '/zultys-support') return <Support />;
    if (normalizedPath === '/fort-worth-zultys-on-premise') return <OnPremise />;
    if (normalizedPath === '/fort-worth-zultys-hybrid') return <Hybrid />;
    if (normalizedPath === '/fort-worth-zultys-contact-center') return <ContactCenter />;
    if (normalizedPath === '/fort-worth-zultys-support') return <Support />;
    if (normalizedPath === '/fort-worth-zultys-installation') return <Installation />;
    if (normalizedPath === '/fort-worth-zultys-training') return <Training />;
    
    if (normalizedPath === '/addison-tx-zultys-phone-systems' || normalizedPath === '/addison') return <Addison />;
    if (normalizedPath === '/aledo-tx-zultys-phone-systems' || normalizedPath === '/aledo') return <Aledo />;
    if (normalizedPath === '/blue-mound-tx-zultys-phone-systems' || normalizedPath === '/blue-mound') return <BlueMound />;

    // Fallback for other paths
    return <NotFound />;
  };

  return (
    <QuoteProvider>
      {renderPage()}
      <Toaster position="top-right" richColors />
      <QuotePopupWrapper />
    </QuoteProvider>
  );
}
